language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dfqalves
  password:
    secure: jT/460h3W9714PByguYl6ebR1+3C/ezFq0fHj3wDoAX+hZ6kyFuH6wQLa2he8fa5iaisLIoDMSAWw89mdmPJ/P5EcmtbQGbTD8v9p3EELEKgwzeMwV+f0A1V9h1OwAcNMlxhdYHXmYfMykzgGyqVXqwEe5qYAkGm3M2tDzXFeEJWp2lCUb+zUQ1LQz1xBblfxMQWMve1OptdTT25LCRMcUGrDhn4W5Cy2O1j28zw0dYvRAjOYSvu8z5N4pQCWbUiQRG7aka+jHwd1UAPUYnyRtQmo7/EsIFbdVLnUNgMM1AqwPI9Gsk7Gf0Vieirgtv4145er0s+41UzHBmWM4G68FsxFFDqz34M6Eknr9Kq435XrKDiiAuuovegXfkYnW78ZSVpcOwhcs7uGkH7AbV5+AIqNzp0SqITXgHspQfAwB9FlxF9NF0w3tuXYZBoWoPjxdFdAhE8x/6KOu1IDOyzIv1Smw5SLXmPVB3eyN26/qFgFRh8KPmY48pMWlFwB/qVyF+U1+YEwKDeFUIH+WPCMuqQnZ9OqSBhps3hUjcHxGNA0h5ymh25jZjMp48YTooF8zGhAZ0uqmnQsv7PCskn1Zt789+/7txJou35wPZZ9+Xrcv71yM+AYHaPkk9/M5SUuOm44tY1YnWoac+V8pZFp8k1mzkjgG7KUynQltphL3Y=
  on:
    tags: true
    repo: diego-alves/hello_cookiecutter
    python: 3.6
